{"name": "Click icon on header -- @1.1 ", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56427): Max retries exceeded with url: /session/6d77a9c3881c31a998aff4c3e29965be/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB046201F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\initialize_driver_website_steps.py\", line 7, in step_load_website\n    web_page.load_website()\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\framework\\initialize_driver_website.py\", line 35, in load_website\n    self.driver.get(base_data[\"url\"])\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 455, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given I load the website", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56427): Max retries exceeded with url: /session/6d77a9c3881c31a998aff4c3e29965be/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB046201F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\initialize_driver_website_steps.py\", line 7, in step_load_website\n    web_page.load_website()\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\framework\\initialize_driver_website.py\", line 35, in load_website\n    self.driver.get(base_data[\"url\"])\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 455, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1670219711564, "stop": 1670219727991}, {"name": "When I try click /html/body/div/div[2]/div[2]/div/div[2]/div/div[1]/ul/li[1]", "status": "skipped", "start": 1670219727992, "stop": 1670219727992}, {"name": "Then I see this component /html/body/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[1]/div/div", "status": "skipped", "start": 1670219727992, "stop": 1670219727992}], "parameters": [{"name": "header_icon", "value": "/html/body/div/div[2]/div[2]/div/div[2]/div/div[1]/ul/li[1]"}, {"name": "component", "value": "/html/body/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div[1]/div/div"}], "start": 1670219711562, "stop": 1670219727992, "uuid": "5ec870bf-c4b2-4a00-93c8-b96e1505cdb9", "historyId": "474c5e54155f312a341d7bc61a1e5bbb", "fullName": "Test the header icons functionality: Click icon on header", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test the header icons functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}