{"name": "Search field", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56427): Max retries exceeded with url: /session/6d77a9c3881c31a998aff4c3e29965be/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB046C14C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\initialize_driver_website_steps.py\", line 7, in step_load_website\n    web_page.load_website()\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\framework\\initialize_driver_website.py\", line 35, in load_website\n    self.driver.get(base_data[\"url\"])\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 455, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given I load the website", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=56427): Max retries exceeded with url: /session/6d77a9c3881c31a998aff4c3e29965be/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CB046C14C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\initialize_driver_website_steps.py\", line 7, in step_load_website\n    web_page.load_website()\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\framework\\initialize_driver_website.py\", line 35, in load_website\n    self.driver.get(base_data[\"url\"])\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 455, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 442, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 294, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 316, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Me\\PycharmProjects\\projectWithBDD\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1670219744362, "stop": 1670219760736}, {"name": "When I write Spain in the search field", "status": "skipped", "start": 1670219760738, "stop": 1670219760739}, {"name": "Then I see this component /html/body/div/div[2]/div[1]/div/div[1]/div[2]/div/div/div[1]/div/div[1]/div/div", "status": "skipped", "start": 1670219760739, "stop": 1670219760739}, {"name": "And I compare search text Spain with result /html/body/div/div[2]/div[1]/div/div[1]/div[2]/div/div/div[1]/div/div[1]/div/div", "status": "skipped", "start": 1670219760739, "stop": 1670219760739}], "start": 1670219744362, "stop": 1670219760739, "uuid": "fc543e7e-67de-4b60-9d3f-8c8f72d4bdb5", "historyId": "eb2e944479fffea7debb9338a3171d5e", "fullName": "Test the header icons functionality: Search field", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test the header icons functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}